// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.22.2";

// src/lib/mcp/tools/list-products.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z } from "npm:zod@^3.25.76";
var STOREFRONT_URL = "https://utn4ey-gy.myshopify.com/api/2025-07/graphql.json";
var STOREFRONT_TOKEN = "2b681057ebd05be63b0cba68fca7cbf3";
var QUERY = `
  query ListProducts($first: Int!) {
    products(first: $first) {
      edges {
        node {
          title
          handle
          description
          priceRange { minVariantPrice { amount currencyCode } }
        }
      }
    }
  }
`;
var list_products_default = defineTool({
  name: "list_products",
  title: "List shop products",
  description: "List products from the Oberkogler Alm online shop (title, handle, price, short description).",
  inputSchema: {
    limit: z.number().int().min(1).max(50).default(20).describe("Maximum number of products to return.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: true },
  handler: async ({ limit }) => {
    const res = await fetch(STOREFRONT_URL, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "X-Shopify-Storefront-Access-Token": STOREFRONT_TOKEN
      },
      body: JSON.stringify({ query: QUERY, variables: { first: limit } })
    });
    if (!res.ok) {
      return { content: [{ type: "text", text: `Shopify error: HTTP ${res.status}` }], isError: true };
    }
    const data = await res.json();
    const products = (data?.data?.products?.edges ?? []).map((e) => ({
      title: e.node.title,
      handle: e.node.handle,
      description: (e.node.description ?? "").slice(0, 400),
      price: `${e.node.priceRange.minVariantPrice.amount} ${e.node.priceRange.minVariantPrice.currencyCode}`,
      url: `https://alm-shop-bloom.lovable.app/product/${e.node.handle}`
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(products, null, 2) }],
      structuredContent: { products }
    };
  }
});

// src/lib/mcp/tools/get-product.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z2 } from "npm:zod@^3.25.76";
var STOREFRONT_URL2 = "https://utn4ey-gy.myshopify.com/api/2025-07/graphql.json";
var STOREFRONT_TOKEN2 = "2b681057ebd05be63b0cba68fca7cbf3";
var QUERY2 = `
  query GetProduct($handle: String!) {
    productByHandle(handle: $handle) {
      title
      handle
      description
      priceRange { minVariantPrice { amount currencyCode } }
      variants(first: 50) {
        edges { node { title price { amount currencyCode } availableForSale } }
      }
      images(first: 5) { edges { node { url altText } } }
    }
  }
`;
var get_product_default = defineTool2({
  name: "get_product",
  title: "Get product details",
  description: "Get full details for a single Oberkogler Alm shop product by its handle (slug).",
  inputSchema: {
    handle: z2.string().min(1).describe("The product handle, e.g. 'ringelblumen-salbe'.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: true },
  handler: async ({ handle }) => {
    const res = await fetch(STOREFRONT_URL2, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "X-Shopify-Storefront-Access-Token": STOREFRONT_TOKEN2
      },
      body: JSON.stringify({ query: QUERY2, variables: { handle } })
    });
    if (!res.ok) {
      return { content: [{ type: "text", text: `Shopify error: HTTP ${res.status}` }], isError: true };
    }
    const data = await res.json();
    const p = data?.data?.productByHandle;
    if (!p) {
      return { content: [{ type: "text", text: `No product found with handle '${handle}'.` }], isError: true };
    }
    const product = {
      title: p.title,
      handle: p.handle,
      description: p.description,
      price: `${p.priceRange.minVariantPrice.amount} ${p.priceRange.minVariantPrice.currencyCode}`,
      variants: p.variants.edges.map((e) => ({
        title: e.node.title,
        price: `${e.node.price.amount} ${e.node.price.currencyCode}`,
        availableForSale: e.node.availableForSale
      })),
      images: p.images.edges.map((e) => e.node.url),
      url: `https://alm-shop-bloom.lovable.app/product/${p.handle}`
    };
    return {
      content: [{ type: "text", text: JSON.stringify(product, null, 2) }],
      structuredContent: { product }
    };
  }
});

// src/lib/mcp/tools/get-opening-hours.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.22.2";
var get_opening_hours_default = defineTool3({
  name: "get_opening_hours",
  title: "Get opening hours & contact",
  description: "Return the Oberkogler Alm opening hours, kitchen hours, seasonal info, address, phone and email.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const info = {
      name: "Oberkogler Alm",
      address: {
        street: "W\xF6rschachberg 63",
        postalCode: "8942",
        city: "W\xF6rschach",
        country: "\xD6sterreich"
      },
      phone: "+43 677 61861537",
      website: "https://alm-shop-bloom.lovable.app",
      season: "Die Alm ist von April bis Ende September ge\xF6ffnet.",
      openingHours: {
        Montag: "10:00\u201318:00",
        Dienstag: "10:00\u201318:00",
        Mittwoch: "Ruhetag",
        Donnerstag: "10:00\u201318:00",
        Freitag: "10:00\u201318:00",
        Samstag: "10:00\u201318:00",
        Sonntag: "10:00\u201318:00"
      },
      kitchenHours: "10:00\u201317:00 (Mittwoch Ruhetag)"
    };
    return {
      content: [{ type: "text", text: JSON.stringify(info, null, 2) }],
      structuredContent: info
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "oberkogler-alm-mcp",
  title: "Oberkogler Alm",
  version: "0.1.0",
  instructions: "Tools for the Oberkogler Alm (a mountain hut in W\xF6rschach, Austria). Use `list_products` and `get_product` to browse the online shop (jams, honey, salves, vouchers, merchandise). Use `get_opening_hours` for opening hours, kitchen times, seasonal info and contact details.",
  tools: [list_products_default, get_product_default, get_opening_hours_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.22.2/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
